name: Pylint

on:
  workflow_run:
    workflows: ["Pylint"]
    types:
      - completed


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: dedreira_awesomecalculator-1.0.0-py3-none-any.whl
        path: src/dist

    - name: Install Artifact
      run: |
          pip install src/dist/dedreira_awesomecalculator-1.0.0-py3-none-any.whl
